# Generated by Django 4.2.6 on 2023-11-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.CharField(max_length=3)),
                ('id_description', models.CharField(max_length=12)),
            ],
        ),
    ]
