# Generated by Django 4.2.6 on 2023-11-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='id',
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
