# Generated by Django 4.2.6 on 2023-11-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_rol_id_alter_rol_id_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='id_description',
            new_name='rol_description',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='id_rol',
            new_name='rol_id',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('user_lastname', models.CharField(max_length=20)),
                ('user_mail', models.CharField(max_length=30)),
                ('user_fono', models.IntegerField()),
                ('user_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rol')),
            ],
        ),
    ]
