# Generated by Django 4.2.6 on 2023-11-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_id_description_rol_rol_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('veh_patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('veh_marca', models.CharField(max_length=15)),
                ('veh_modelo', models.CharField(max_length=25)),
                ('veh_anno', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
