# Generated by Django 4.2.6 on 2023-11-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('ate_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_nom', models.CharField(max_length=20)),
                ('pro_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('rep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rep_nom', models.CharField(max_length=50)),
                ('rep_anno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('ser_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ser_desc', models.CharField(max_length=50)),
                ('ser_prec', models.IntegerField()),
                ('ser_durac', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ped_id', models.AutoField(primary_key=True, serialize=False)),
                ('ped_est', models.CharField(choices=[('En Proceso', 'En Proceso'), ('Solicitado', 'Solicitado'), ('Cancelado', 'Cancelado'), ('Entregado', 'Entregado')], default='En Proceso', max_length=12)),
                ('ped_fecha', models.DateTimeField(auto_now_add=True)),
                ('ate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.atencion')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_precio', models.IntegerField()),
                ('ser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicio')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.carrito'),
        ),
    ]
