# Generated by Django 4.2.6 on 2023-11-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_atencion_proveedor_repuestos_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='ate_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='atencion',
            name='ate_list',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='atencion',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='ate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together={('ate_date',)},
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='car_id',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
