# Generated by Django 4.2.6 on 2023-11-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_repuestos_ped_id_repuestos_rep_marc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='pro_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='rep_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ser_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='veh_anno',
            field=models.CharField(max_length=4),
        ),
    ]
