# Generated by Django 4.2.6 on 2023-11-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_inventario_rename_user_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_rol',
            new_name='rol_id',
        ),
    ]
