# Generated by Django 4.2.6 on 2023-11-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_user_rol_userprofile_rol_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='user_id',
            new_name='userProfile',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='ate_id',
            new_name='atencion',
        ),
        migrations.RenameField(
            model_name='repuestos',
            old_name='ped_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='rol_id',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='user_id',
            new_name='userProfile',
        ),
    ]
