# Generated by Django 4.2.6 on 2023-11-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_user_id_atencion_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='rep_anno',
            field=models.CharField(max_length=4),
        ),
    ]
