# Generated by Django 4.2.6 on 2023-11-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_repuestos_rep_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_password',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
