# Generated by Django 4.2.6 on 2023-11-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userprofile_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='veh_img',
            field=models.ImageField(blank=True, null=True, upload_to='veh_img/'),
        ),
    ]
