# Generated by Django 4.2.6 on 2023-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_vehiculo_veh_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='ate_prec',
            field=models.IntegerField(default=None),
        ),
    ]
