# Generated by Django 4.2.6 on 2023-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_atencion_ate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='ate_est',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Solicitado', 'Solicitado'), ('Cancelado', 'Cancelado'), ('Entregado', 'Entregado')], default='En Proceso', max_length=12),
        ),
    ]
