# Generated by Django 4.2.6 on 2023-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_atencion_ate_est'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='ate_est',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('En Proceso', 'En Proceso'), ('Cancelada', 'Cancelada'), ('Realizada', 'Realizada')], default='Solicitada', max_length=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ped_est',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Cancelado', 'Cancelado'), ('Entregado', 'Entregado')], default='Solicitado', max_length=12),
        ),
    ]
