# Generated by Django 4.2.6 on 2023-12-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_atencion_ate_est_alter_pedido_ped_est'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuestos',
            name='pedido',
        ),
    ]
