# Generated by Django 4.2.6 on 2023-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_repuestos_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='rep_anno',
            field=models.CharField(max_length=4),
        ),
    ]
