# Generated by Django 4.2.6 on 2023-12-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_inventario_rep_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='rep_anno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='rep_anno',
            field=models.IntegerField(),
        ),
    ]
